### ISSUE TITLE
After completing the class name, the format of the class is incorrect

### ISSUE THREAD

**Issue by Dramas7** [Tarrowren/css-class-intellisense#12]
When the class name(class selector) is automatically completed, it should be in this format: "**.foo**".
But actually its format is: "**..foo**".
When I use the completion feature, I have to remove a **"."** to ensure the correct format of the class name.
Fortunately, after completing the id selector, the format is correct.

**Comment by Dramas7** [comment]
Additional instructions:  
<kbd>.</kbd> to trigger intellisense, then <kbd>tab</kbd> it, the edit area will get an incorrect class name format.  

I have used this extension for two years, versions below 3.x didn't have such issues.  

There are no CSS completing extension as good as **css-class-intellisense** in VsCode.
I really hope it gets better.

**Comment by Tarrowren** [comment]
Please try version 4.3.1

**Comment by Dramas7** [comment]
I have tried the latest release, awesome!!!!!!!!!!!!!
