### ISSUE TITLE
Feature Request: Support for PHP Files and Customizable File Types

### ISSUE THREAD

**Issue by mytory** [Tarrowren/css-class-intellisense#13]
Dear Tarrowren.

First of all, I would like to express my gratitude for creating such an excellent extension. The functionality it provides is superior to other CSS extensions available, as it supports code completion, "Go to definition," and "Rename" features. These capabilities truly set it apart from the competition.

However, there is one limitation that I find somewhat disappointing: the extension only works with Html, Vue, and Jsx files. As a PHP developer, I would be extremely grateful if you could extend its functionality to also work with PHP files. Alternatively, providing an option for users to customize which file types the extension can be applied to would also be greatly appreciated.

Thank you once again for your hard work on this outstanding extension. I look forward to seeing what future updates have in store.

Kind regards,
An Hyeong-woo.

**Comment by Tarrowren** [comment]
see 4.4.0.
I am not familiar with PHP, please alert me if there are any bugs
