### ISSUE TITLE
使用该插件打开PHP项目会导致vscode卡死

### ISSUE THREAD

**Issue by zzy-life** [Tarrowren/css-class-intellisense#17]

**Comment by Tarrowren** [comment]
Can you provide a demo project and list all enabled extensions?

**Comment by Tarrowren** [comment]
Can you try this setting item?
```json
{
    "cssci.lightweight": true
}
```

**Comment by zzy-life** [comment]
> Can you try this setting item?
> 
> ```json
> {
>     "cssci.lightweight": true
> }
> ```

Seems to have solved the problem
