### ISSUE TITLE
该插件会导致 vue 文件不能重命名符号

### ISSUE THREAD

**Issue by tohere** [Tarrowren/css-class-intellisense#19]
<img width="571" alt="image" src="https://github.com/user-attachments/assets/9e4ef6b2-da6c-40d1-9003-77dcff144ec9">

如图, 卸载了好多插件才找到原因..., 不知道是什么原因导致的

**Comment by Tarrowren** [comment]
![image](https://github.com/user-attachments/assets/b67bf1b6-af0c-46ce-8750-b33ff5cdffb4)
我的没毛病啊，你的vscode、插件版本是多少

**Comment by tohere** [comment]
vscode 是最新的版本, 这个插件也是最新版本, 如果只有我有这个问题的话, 可能是多个插件互相有影响吧

**Comment by Tarrowren** [comment]
你用vscode的配置文件新建一个最少插件的配置，能复现问题的话把插件列表发我我看下

**Comment by tohere** [comment]
<img width="830" alt="image" src="https://github.com/user-attachments/assets/0e3c8f5b-e588-4529-ba1f-b7f01df3483b">
已经禁掉了除了 vue 和这个插件的所有插件, 还是不行, 我用的 mac

**Comment by Tarrowren** [comment]
更新后配置 "cssci.languages.vue": false，我发现官方插件已经支持类名提示了

**Comment by tohere** [comment]
好的, 谢谢
